// js/dom.js
export const dom = {
    pauseBtn: document.getElementById('pause-btn'),
    resumeBtn: document.getElementById('resume-btn'),
    pauseSettingsBtn: document.getElementById('pause-settings-btn'),
    quitBtn: document.getElementById('quit-btn'),
    sbPrev: document.getElementById('sb-prev'),
    sbNext: document.getElementById('sb-next'),
    sbSpeedBtn: document.getElementById('sb-speed-btn'),
    sbResetCooldowns: document.getElementById('sb-reset-cooldowns'),
    sbViewToggle: document.getElementById('sb-view-toggle'),
    camoToggleBtn: document.getElementById('sb-toggle-camo'),
    regenToggleBtn: document.getElementById('sb-toggle-regen'),
    fortToggleBtn: document.getElementById('sb-toggle-fortified'),
    enemyCards: document.querySelectorAll('#enemy-view .tower-card[data-enemy]'),
    towerCards: document.querySelectorAll('.tower-card[data-tower]'),
    waveSpeedBtn: document.getElementById('wave-speed-btn'),
    upTargetPrev: document.getElementById('up-target-prev'),
    upTargetNext: document.getElementById('up-target-next'),
    upBuyLevel: document.getElementById('up-buy-level'),
    upPaths: [
        document.getElementById('up-path1'),
        document.getElementById('up-path2'),
        document.getElementById('up-path3')
    ],
    upSell: document.getElementById('up-sell'),
    upCollectBank: document.getElementById('up-collect-bank'),
    cashDisplay: document.getElementById('cash-display'),
    livesDisplay: document.getElementById('lives-display'),
    waveDisplay: document.getElementById('wave-display'),
    cancelBtn: document.getElementById('cancel-btn'),
    btnMonkeys: document.getElementById('btn-monkeys'),
    btnHeroes: document.getElementById('btn-heroes'),
    btnPlay: document.getElementById('btn-play'),
    btnSandbox: document.getElementById('btn-sandbox'),
    btnPowers: document.getElementById('btn-powers'),
    btnKnowledge: document.getElementById('btn-knowledge'),
    mmTopLeft: document.getElementById('mm-top-left'),
    btnSettings: document.getElementById('btn-settings'),
    btnMapEditor: document.getElementById('btn-map-editor'),
    btnContinue: document.getElementById('btn-continue'),
    btnAbandon: document.getElementById('btn-abandon'),
    diffBtns: document.querySelectorAll('.diff-btn[data-diff]'),
    hmPrevBtn: document.getElementById('hm-prev-btn'),
    hmNextBtn: document.getElementById('hm-next-btn'),
    heroSelector: document.getElementById('hero-selector'),
    settingsBackBtn: document.getElementById('settings-back-btn'),
    goMenuBtn: document.getElementById('go-menu-btn'),
    backBtns: document.querySelectorAll('.back-btn[data-target]'),
    volumeSlider: document.getElementById('volume-slider'),
    volDisplay: document.getElementById('vol-display'),
    musicSlider: document.getElementById('music-slider'),
    musicVolDisplay: document.getElementById('music-vol-display'),
    bgRunCheckbox: document.getElementById('bg-run-checkbox'),
    autoWaveMenu: document.getElementById('auto-wave-checkbox-menu'),
    autoWavePause: document.getElementById('auto-wave-checkbox-pause'),
    flavorTextCheckbox: document.getElementById('flavor-text-checkbox'),
    smoothingCheckbox: document.getElementById('smoothing-checkbox'),
    fpsCheckbox: document.getElementById('fps-checkbox'),
    fpsDisplay: document.getElementById('fps-display'),
    extremeSpeedCheckbox: document.getElementById('extreme-speed-checkbox'),
    shuffleMusicCheckbox: document.getElementById('shuffle-music-checkbox'),
    randomStartCheckbox: document.getElementById('random-start-checkbox'),
    showStatsCheckbox: document.getElementById('show-stats-checkbox'),
    uncapFpsCheckbox: document.getElementById('uncap-fps-checkbox'),
    showHitboxesCheckbox: document.getElementById('show-hitboxes-checkbox'),
    prevSongBtn: document.getElementById('prev-song-btn'),
    nextSongBtn: document.getElementById('next-song-btn'),
    pausePrevSong: document.getElementById('pause-prev-song'),
    pauseNextSong: document.getElementById('pause-next-song')
};