// js/spriteConfig.js
export const SpriteConfig = {
    "ace": { "base": { "x": 0, "y": 3, "scale": 1.7 } },
    "alchemist": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "boomerang": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "boomerang_p1_t1": { "base": { "x": 3.5, "y": 3, "scale": 1.3 } },
    "boomerang_p2_t3": { "base": { "x": 6.5, "y": -3.5, "scale": 1.2 } },
    "buccaneer": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "dart": {
        "base": { "x": 1.5, "y": 3, "scale": 1 },
        "arm": { "x": 2, "y": 2, "scale": 1 },
        "attack_1": { "x": 2, "y": 2, "scale": 1 },
        "attack_2": { "x": 2, "y": 2, "scale": 1 },
        "attack_3": { "x": 2, "y": 2, "scale": 1 },
        "attack_4": { "x": 2, "y": 2, "scale": 1 },
        "attack_5": { "x": 2, "y": 2, "scale": 1 },
        "attack_6": { "x": 2, "y": 2, "scale": 1 },
        "attack_7": { "x": 2, "y": 2, "scale": 1 },
        "attack_8": { "x": 2, "y": 2, "scale": 1 },
        "attack_9": { "x": 2, "y": 2, "scale": 1 }
    },
    "dart_p1_t3": {
        "base": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_0": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_1": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_2": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_3": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_4": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_5": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_6": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_7": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_8": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_9": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_10": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_11": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_12": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_13": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_14": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_15": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_16": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_17": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_18": { "x": -5.5, "y": -10, "scale": 2 },
        "attack_full_19": { "x": -5.5, "y": -10, "scale": 2 }
    },
    "dart_p3_t3": { "base": { "x": 1.5, "y": -1, "scale": 1.2 } },
    "engineer": { "base": { "x": 0.5, "y": -3, "scale": 1.25 } },
    "farm": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "geto": { "base": { "x": 0, "y": 6, "scale": 1 } },
    "glue": {
        "base": { "x": 3.5, "y": 0, "scale": 1.2 },
        "arm": { "x": 2.5, "y": -4.5, "scale": 1 }
    },
    "gojo": { "base": { "x": 0, "y": 6, "scale": 1 } },
    "gwendolin": { "base": { "x": 2.25, "y": -3, "scale": 1.2 } },
    "ice": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "ice_p2_t3": { "base": { "x": 0, "y": 6, "scale": 1 } },
    "mortar": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "quincy": {
        "base": { "x": 2.25, "y": -3, "scale": 1.2 },
        "arm": { "x": 2.25, "y": -3, "scale": 1.2 }
    },
    "sniper": {
        "base": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_0": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_1": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_2": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_3": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_4": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_5": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_6": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_7": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_8": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_9": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_10": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_11": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_12": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_13": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_14": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_15": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_16": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_17": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_18": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_19": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_20": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_21": { "x": -2.5, "y": -5.5, "scale": 3.25 },
        "attack_full_22": { "x": -2.5, "y": -5.5, "scale": 3.25 }
    },
    "spike": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "sub": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "super": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "village": { "base": { "x": 1.5, "y": 3, "scale": 1 } },
    "wizard": { "base": { "x": 1.5, "y": 3, "scale": 1 } }
};