// js/webgl/pixiRenderer.js
import { Texture } from 'pixi.js';
import { PixiApp } from './pixiApp.js';
import { PixiAssets } from './pixiAssets.js';
import { TowersRenderer } from './renderTowers.js';
import { EnemiesRenderer } from './renderEnemies.js';
import { ProjectilesRenderer } from './renderProjectiles.js';
import { WorldRenderer } from './renderWorld.js';
import { UIRenderer } from './renderUI.js';
import { HeroVFXRenderer } from './renderHeroVFX.js';
import { CutsceneRenderer } from './renderCutscene.js';
import { MenuRenderer } from './renderMenu.js';
import { BuffIconsRenderer } from './renderBuffIcons.js';
import { TowerStats } from '../towers/index.js';
import { HeroRegistry } from '../heroes/index.js';
import { Maps } from '../data.js';
import { SPRITESHEETS } from '../spriteSheets.js';

export const PixiRenderer = {
    _bgSprite: null,
    _towerSprites: new Map(),
    _enemySprites: new Map(),
    _projectileSprites: new Map(),
    _towerEffectSprites: new Map(),
    _particleSprites: new Map(),
    _beastSprites: new Map(),
    _sentrySprites: new Map(),
    _explosionsGraphics: null,
    _acidPoolGraphics: new Map(),
    _floatingTextsLayer: null,
    _floatingTextSprites: new Map(),
    _selectionGraphics: null,
    _leakFlashGraphics: null,
    _hitscansGraphics: null,
    _bananaSprites: new Map(),
    _bossBarEntries: new Map(),
    _cursorGraphics: null,
    _bossWarningLineGraphics: null,
    _hitboxGraphics: null,
    _devOverlayText: null,
    _devOverlayBg: null,
    _erroredMethods: new Set(),

    async init(canvasEl) {
        await PixiApp.init(canvasEl);
        this._preloadSprites();
    },

    // PixiAssets loads lazily (a get() returns Texture.EMPTY until the asset
    // finishes loading), so any sprite that isn't preloaded is invisible for
    // a frame or two on its FIRST use — that's what made the cutscene slash
    // (and knight, stun rings, cracks, first-spawned towers/enemies) "blink"
    // on first appearance, and an UPGRADED sniper show a blank square until
    // its upgrade-specific attack frames (sniper_pX_tY_attack_full_*) finished
    // a late decode + GPU upload mid-round. This preloads every key the
    // renderers can request so no mid-game load is ever triggered.
    //
    // Tower/hero attack frames (base + every upgrade prefix) come from
    // sprites/manifest.json (generated by tools/gen-manifest.mjs), so newly
    // added sprites preload automatically. Sheeted frames come from
    // SPRITESHEETS; enemies/effects/projectiles/maps use the static lists.
    // Missing keys are harmless (PixiAssets marks them missing and logs once),
    // so the list is intentionally generous.
    // Fetches (and caches) sprites/manifest.json — the generated index of every
    // loose tower/hero attack frame. Shared by the WebGL and canvas preloads.
    async fetchManifest() {
        if (!this._manifestPromise) {
            this._manifestPromise = fetch('sprites/manifest.json')
                .then(r => r.json())
                .catch(err => { this._manifestPromise = null; throw err; });
        }
        return this._manifestPromise;
    },

    async _buildPreloadKeys() {
        const keys = [];
        for (const type of Object.keys(TowerStats)) keys.push(`tower_${type}_base`, `tower_${type}_arm`);
        for (const type of Object.keys(HeroRegistry)) keys.push(`tower_${type}_base`, `tower_${type}_arm`);

        // Manifest-driven tower/hero attack frames (base + every upgrade).
        try {
            const manifest = await this.fetchManifest();
            const pushFrames = (frames) => {
                for (const f of frames || []) {
                    const file = String(f.url).split('/').pop();
                    if (file) keys.push(`tower_${file.replace(/\.png$/, '')}`);
                }
            };
            for (const entry of Object.values(manifest.towers || {})) {
                pushFrames(entry.frames);
                for (const upg of Object.values(entry.upgrades || {})) {
                    if (upg.base) keys.push(`tower_${upg.base.split('/').pop().replace(/\.png$/, '')}`);
                    pushFrames(upg.frames);
                }
            }
        } catch (err) {
            console.warn('[PixiRenderer] manifest preload failed (static lists only):', err);
        }

        // Sheeted frames: every tower attack sheet frame, plus representative
        // keys for the frame-count-0 atlases (moab/bfb/effects) — loading one
        // key fetches the whole atlas, so every other frame of that sheet then
        // extracts instantly from the cached sheet instead of hitting the net.
        const REP_SHEET_KEYS = {
            'enemy_moab': ['enemy_moab', 'enemy_moab_1', 'enemy_moab_blades_0', 'enemy_moab_blades_2_0'],
            'enemy_bfb': ['enemy_bfb', 'enemy_bfb_1', 'enemy_bfb_blades_0', 'enemy_bfb_blades_3_0'],
            'effect_': ['effect_pop', 'effect_slash_1', 'effect_stun_1', 'effect_banana'],
        };
        for (const entry of SPRITESHEETS) {
            if (entry.frameCount > 0) {
                for (let i = 0; i < entry.frameCount; i++) keys.push(`${entry.prefix}${i}`);
            } else if (REP_SHEET_KEYS[entry.prefix]) {
                keys.push(...REP_SHEET_KEYS[entry.prefix]);
            }
        }

        // Loose non-full attack frames (the manifest only tracks _attack_full_).
        for (let i = 0; i < 10; i++) keys.push(`tower_dart_attack_${i}`);

        // Enemies: body + camo/regen variants + damage cracks + blades.
        const enemyNames = ['red', 'blue', 'green', 'yellow', 'pink', 'black', 'white', 'lead', 'zebra', 'purple', 'rainbow', 'ceramic', 'moab', 'bfb', 'zomg', 'ddt', 'bad'];
        for (const name of enemyNames) keys.push(`enemy_${name}`, `enemy_${name}_camo`, `enemy_${name}_regen`, `enemy_${name}_regen_camo`);
        for (const name of ['ceramic', 'moab', 'bfb', 'zomg', 'ddt', 'bad']) for (let s = 1; s <= 3; s++) keys.push(`enemy_${name}_${s}`);
        // MOAB-class blade frames (ZOMG is loose; MOAB/BFB resolve via atlas).
        for (let f = 0; f <= 4; f++) keys.push(`enemy_zomg_blades_${f}`);

        // Effects.
        keys.push(
            'effect_banana', 'effect_banana_crate',
            'effect_camo_effect', 'effect_camo_regen_effect',
            'effect_frozen_effect', 'effect_frozen_effect_lead', 'effect_frozen_effect_regen',
            'effect_fortified',
            'effect_pop', 'effect_pop2', 'effect_pop3'
        );
        for (let i = 1; i <= 14; i++) keys.push(`effect_slash_${i}`);
        for (let i = 1; i <= 15; i++) keys.push(`effect_stun_${i}`);

        // Knight: cutscene roar (knight_back_1..19) + equip_sword (1..20)
        // frames in sprites/boss/, plus the static front used for the fight
        // and trail ghosts.
        keys.push('enemy_knight_front');
        for (let i = 1; i <= 19; i++) keys.push(`boss_knight_back_${i}`);
        for (let i = 1; i <= 20; i++) keys.push(`boss_equip_sword_${i}`);
        // Ball-morph reposition: collapse/roll/reform frames in sprites/boss/.
        for (let i = 1; i <= 4; i++) keys.push(`boss_ball_transition_${i}`);
        for (let i = 1; i <= 5; i++) keys.push(`boss_ball_${i}`);
        // In-fight knight sprite anims: slash, point, static.
        for (let i = 1; i <= 5; i++) keys.push(`boss_slash_${i}`);
        for (let i = 1; i <= 5; i++) keys.push(`boss_point_${i}`);
        for (let i = 1; i <= 3; i++) keys.push(`boss_static_${i}`);
        // Death-exit fly-away: fly_transition (1..17) then fly loop (1..4).
        for (let i = 1; i <= 17; i++) keys.push(`boss_fly_transition_${i}`);
        for (let i = 1; i <= 4; i++) keys.push(`boss_fly_${i}`);
        for (const proj of ['arrow', 'blade', 'bomb', 'boomerang', 'dart', 'fire', 'glue', 'ice_shard', 'javelin', 'juggernaut', 'knightsword', 'mortar_shell', 'nail', 'potion', 'shuriken', 'slash', 'spike', 'spike_opult', 'squid', 'sunavatarbeam', 'super', 'tack', 'ultra_juggernaut', 'ultra_juggernaut_sub', 'wizard_bolt', 'worm']) {
            keys.push(`proj_${proj}`);
        }
        for (let i = 0; i <= 15; i++) keys.push(`proj_meteor_${i}`);

        // Map backgrounds (and their night variants) — iterate the live map
        // list so newly added maps preload automatically too.
        for (const mapData of Maps) {
            if (!mapData || !mapData.image) continue;
            keys.push(`map_${mapData.image}`);
            keys.push(mapData.imageNight ? `map_${mapData.imageNight}` : `map_${mapData.image}_night`);
        }

        return keys;
    },

    // Await-able full preload used by the loading screen. Idempotent (the
    // fire-and-forget _preloadSprites may already have loaded most of these).
    // Quiet: the generous lists include optional sprites (arms, camo/regen
    // variants) that legitimately 404, and those shouldn't spam the console.
    async preloadGameAssets(onProgress) {
        const keys = await this._buildPreloadKeys();
        await PixiAssets.preloadManifest(keys, onProgress, true);
    },

    // Canvas-side equivalents of the manifest-driven frames. The tower's
    // animation-decision logic (towerBehavior._getAnimationAsset) probes
    // Assets.get() (js/assets.js) for these same keys on the FIRST shot; if
    // the loose images haven't decoded yet it falls back to base-only for a
    // shot or two — the "first shot cut off / slower than the rest" symptom.
    // Preloading them makes shot #1 use the full animation. Sheeted frames
    // resolve instantly (sheetHasFrame returns a dummy loaded image), loose
    // ones load for real; either way the decision settles on the first shot.
    async towerFrameKeys() {
        const keys = [];
        try {
            const manifest = await this.fetchManifest();
            const pushFrames = (frames) => {
                for (const f of frames || []) {
                    const file = String(f.url).split('/').pop();
                    if (file) keys.push(`tower_${file.replace(/\.png$/, '')}`);
                }
            };
            for (const entry of Object.values(manifest.towers || {})) {
                pushFrames(entry.frames);
                for (const upg of Object.values(entry.upgrades || {})) {
                    if (upg.base) keys.push(`tower_${upg.base.split('/').pop().replace(/\.png$/, '')}`);
                    pushFrames(upg.frames);
                }
            }
        } catch (err) {
            console.warn('[PixiRenderer] manifest unavailable for canvas preload:', err);
        }
        // Loose non-full attack frames (the manifest only tracks _attack_full_).
        for (let i = 0; i < 10; i++) keys.push(`tower_dart_attack_${i}`);
        return keys;
    },

    // Background kick-off so the title screen and menu have a head start.
    async _preloadSprites() {
        try {
            await this.preloadGameAssets();
        } catch (err) {
            console.warn('[PixiRenderer] background preload failed:', err);
        }
    },

    // FIX: Added rawDt to pass to the dev overlay for FPS calculation
    render(engine, rawDt) {
        if (engine.canvas) {
            engine.canvas.style.cursor = (engine.gameState === 'playing') ? 'none' : 'auto';
        }

        // Mirror renderer.js's night-mode easing here too: the WebGL pipeline
        // reads engine.nightAlpha (map, tower night-glow, super/druid nightMod),
        // which the Canvas2D renderer updates but this one never did.
        if (engine.isNight === undefined) engine.isNight = false;
        if (engine.nightAlpha === undefined) engine.nightAlpha = 0;
        const targetNightAlpha = engine.isNight ? 1 : 0;
        engine.nightAlpha += (targetNightAlpha - engine.nightAlpha) * Math.min(1, (rawDt || 0.016) * 2);

        // Mirrors renderer.js's early return: `engine.gameState === 'menu'`
        // or no map loaded skips the entire gameplay pipeline below (which
        // assumes a real map/entities exist) in favor of just the menu
        // background + dev overlay. This branch didn't exist at all before
        // — see renderMenu.js's file header for what that actually meant
        // in practice.
        if (engine.gameState === 'menu' || !engine.map) {
            PixiApp.menuLayer.visible = true;
            PixiApp.compositeLayer.visible = false;
            PixiApp.cutsceneLayer.visible = false;
            // worldContainer is a direct child of app.stage (see pixiApp.js)
            // and is left visible=true by the gameplay fast path (renderUI.js
            // _compositeWorld). If we don't hide it here, every leftover world
            // sprite from the previous run (towers, enemies, projectiles,
            // particles) keeps rendering behind the DOM menu every frame.
            PixiApp.worldContainer.visible = false;
            PixiApp.pannedContainer.x = 0;
            this._safeDraw('_drawMainMenuScenery', engine, rawDt);
            this._safeDraw('_drawDevOverlay', engine, rawDt);
            // Cursor/boss-bar/warning-line are meaningless outside a game
            // but are self-clearing (see renderUI.js), so calling them
            // here too guarantees no stale graphics survive from a
            // previous playing session lingering under the menu.
            this._safeDraw('_drawCursor', engine);
            this._safeDraw('_drawBossHealthBar', engine);
            this._safeDraw('_drawBossWarningLine', engine);
            PixiApp.app.renderer.render(PixiApp.app.stage);
            return;
        }
        PixiApp.menuLayer.visible = false;
        PixiApp.compositeLayer.visible = true;
        PixiApp.cutsceneLayer.visible = true;
        PixiApp.worldContainer.visible = true;

        this._safeDraw('_drawBackground', engine);
        this._safeDraw('_drawAcidPools', engine);
        this._safeDraw('_drawExplosions', engine);
        this._safeDraw('_drawTowerEffects', engine);
        this._safeDraw('_drawHeroVFX', engine);
        this._safeDraw('_drawTowers', engine);
        this._safeDraw('_drawBuffIcons', engine);
        this._safeDraw('_drawBeasts', engine);
        this._safeDraw('_drawSentries', engine);
        this._safeDraw('_drawProjectiles', engine);
        this._safeDraw('_drawEnemies', engine);
        this._safeDraw('_drawParticles', engine);
        this._safeDraw('_drawHitscans', engine);
        this._safeDraw('_drawBananas', engine);
        this._safeDraw('_drawFloatingTexts', engine);
        this._safeDraw('_drawPlacementPreview', engine);
        this._safeDraw('_drawLeakFlash', engine);
        this._safeDraw('_drawCutsceneRevealBar', engine);
        this._safeDraw('_drawCutsceneBalls', engine);
        this._safeDraw('_drawBossHealthBar', engine);
        this._safeDraw('_drawBossWarningLine', engine);
        
        // FIX: Added Hitboxes and Dev Overlay
        this._safeDraw('_drawHitboxes', engine);
        this._safeDraw('_drawCursor', engine);
        this._safeDraw('_drawDevOverlay', engine, rawDt);
        this._safeDraw('_drawCutscene', engine);

        // Must run last: captures everything the layers above just drew
        // into worldTexture, composites it (split or not) into
        // compositeLayer, then does the single manual
        // app.renderer.render(app.stage) call for this frame. See
        // pixiApp.js's autoStart:false comment for why this replaced
        // Pixi's own ticker.
        this._safeDraw('_compositeWorld', engine);
    },

    // FIX: Updated _safeDraw to accept and spread extra arguments
    _safeDraw(methodName, ...args) {
        try {
            this[methodName](...args);
        } catch (err) {
            if (!this._erroredMethods.has(methodName)) {
                this._erroredMethods.add(methodName);
                console.error(`[PixiRenderer] ${methodName} threw (further errors from this method this session are suppressed, but it will keep being retried every frame):`, err);
            }
        }
    },

    _sizeUniform(sprite, texture, targetSize) {
        if (texture === Texture.EMPTY) return;
        const maxDim = Math.max(texture.width, texture.height) || 1;
        const scale = targetSize / maxDim;
        sprite.width = texture.width * scale;
        sprite.height = texture.height * scale;
    }
};

// Merge all the rendering modules into the main PixiRenderer object
Object.assign(PixiRenderer, TowersRenderer, EnemiesRenderer, ProjectilesRenderer, WorldRenderer, UIRenderer, HeroVFXRenderer, CutsceneRenderer, MenuRenderer, BuffIconsRenderer);